import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getAppSettings } from "@/lib/appSettings";
import { ThemeSettingsProvider } from "@/components/club/ThemeSettingsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { primaryColor, logoUrl } = await getAppSettings();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{ "--color-primary": primaryColor } as React.CSSProperties}
    >
      <body className="min-h-full flex flex-col">
        <ThemeSettingsProvider logoUrl={logoUrl}>
          {children}
        </ThemeSettingsProvider>
      </body>
    </html>
  );
}
